[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning:pydantic
    ignore::DeprecationWarning:passlib
    ignore:The 'pysnmp-lextudio' package is deprecated:RuntimeWarning
